//! Values written from IDML observation: what every InDesign-exported IDML
//! in the corpus has on the root styles (`root_values.xml`) and in its
//! preferences (`preference_values.xml`), both generated by
//! `tools/root_values.py`. See `docs/format/idml-values.md`.

use super::xml::Xml;

/// An element of the values file.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct Node {
    pub tag: String,
    pub attrs: Vec<(String, String)>,
    pub text: Option<String>,
    pub children: Vec<Node>,
}

impl Node {
    pub fn child(&self, tag: &str) -> Option<&Node> {
        self.children.iter().find(|c| c.tag == tag)
    }

    pub fn attr(&self, name: &str) -> Option<&str> {
        self.attrs
            .iter()
            .find(|(k, _)| k == name)
            .map(|(_, v)| v.as_str())
    }

    /// Add the attributes and children of `other` that `self` lacks.
    /// Children with the same tag are merged.
    fn merge(&mut self, other: &Node) {
        for (k, v) in &other.attrs {
            if self.attr(k).is_none() {
                self.attrs.push((k.clone(), v.clone()));
            }
        }
        if self.text.is_none() {
            self.text = other.text.clone();
        }
        for c in &other.children {
            match self.children.iter_mut().find(|m| m.tag == c.tag) {
                Some(m) => m.merge(c),
                // The schema puts `Properties` before other children.
                None if c.tag == "Properties" => self.children.insert(0, c.clone()),
                None => self.children.push(c.clone()),
            }
        }
    }

    /// Write this element and its children.
    pub fn write(&self, x: &mut Xml) {
        x.start(&self.tag);
        for (k, v) in &self.attrs {
            x.attr(k, v);
        }
        if let Some(t) = &self.text {
            x.text(t);
        }
        for c in &self.children {
            c.write(x);
        }
        x.end();
    }
}

const ROOT_VALUES: &str = include_str!("root_values.xml");

/// The observed values of root style element `tag` (`ParagraphStyle`,
/// `ObjectStyle`, ...) for a document of InDesign version `major`.
pub fn root_style(tag: &str, major: u32) -> Node {
    let mut out = Node {
        tag: tag.to_string(),
        ..Node::default()
    };
    let root = parse(ROOT_VALUES).expect("root_values.xml is well-formed");
    for block in &root.children {
        let since = block
            .attr("MinimumVersion")
            .map_or(0, |v| v.parse().expect("MinimumVersion is a number"));
        if since <= major
            && let Some(n) = block.child(tag)
        {
            out.merge(n);
        }
    }
    out
}

const PREFERENCE_VALUES: &str = include_str!("preference_values.xml");

/// The observed preference elements (`TextDefault`, ...) for a document of
/// InDesign version `major`, in the order the IDML files list them.
pub fn preferences(major: u32) -> Vec<Node> {
    let root = parse(PREFERENCE_VALUES).expect("preference_values.xml is well-formed");
    let mut out: Vec<Node> = Vec::new();
    for block in &root.children {
        let since = block
            .attr("MinimumVersion")
            .map_or(0, |v| v.parse().expect("MinimumVersion is a number"));
        if since > major {
            continue;
        }
        for n in &block.children {
            match out.iter_mut().find(|m| m.tag == n.tag) {
                Some(m) => m.merge(n),
                None => out.push(n.clone()),
            }
        }
    }
    out
}

fn unescape(s: &str) -> String {
    s.replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&apos;", "'")
        .replace("&amp;", "&")
}

/// Parse the small, trusted XML subset of the values file: elements,
/// attributes in single or double quotes, text, comments and the XML
/// declaration.
fn parse(s: &str) -> Option<Node> {
    let mut stack: Vec<Node> = vec![Node::default()];
    let mut rest = s;
    while !rest.is_empty() {
        if let Some(r) = rest.strip_prefix("<?") {
            rest = &r[r.find("?>")? + 2..];
        } else if let Some(r) = rest.strip_prefix("<!--") {
            rest = &r[r.find("-->")? + 3..];
        } else if let Some(r) = rest.strip_prefix("</") {
            rest = &r[r.find('>')? + 1..];
            let done = stack.pop()?;
            stack.last_mut()?.children.push(done);
        } else if let Some(r) = rest.strip_prefix('<') {
            let end = r.find('>')?;
            let (mut head, empty) = match r[..end].strip_suffix('/') {
                Some(h) => (h.trim_end(), true),
                None => (&r[..end], false),
            };
            rest = &r[end + 1..];
            let name_end = head.find(char::is_whitespace).unwrap_or(head.len());
            let mut node = Node {
                tag: head[..name_end].to_string(),
                ..Node::default()
            };
            head = head[name_end..].trim_start();
            while !head.is_empty() {
                let eq = head.find('=')?;
                let key = head[..eq].trim();
                let value = head[eq + 1..].trim_start();
                let quote = value.chars().next()?;
                let close = value[1..].find(quote)? + 1;
                node.attrs
                    .push((key.to_string(), unescape(&value[1..close])));
                head = value[close + 1..].trim_start();
            }
            if empty {
                stack.last_mut()?.children.push(node);
            } else {
                stack.push(node);
            }
        } else {
            let end = rest.find('<').unwrap_or(rest.len());
            let text = &rest[..end];
            if !text.trim().is_empty() {
                stack.last_mut()?.text = Some(unescape(text));
            }
            rest = &rest[end..];
        }
    }
    let mut top = stack.pop()?;
    stack.is_empty().then_some(())?;
    top.children.pop()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_values_subset() {
        let n = parse(
            "<?xml version=\"1.0\"?>\n<!-- c -->\n<A x=\"1 &amp; 2\" y='q\"'>\n\t<B />\n\t<C type=\"string\">t &lt; u</C>\n</A>\n",
        )
        .unwrap();
        assert_eq!(n.tag, "A");
        assert_eq!(n.attr("x"), Some("1 & 2"));
        assert_eq!(n.attr("y"), Some("q\""));
        assert_eq!(n.children.len(), 2);
        assert_eq!(n.child("C").unwrap().text.as_deref(), Some("t < u"));
    }

    #[test]
    fn gates_values_by_version() {
        let old = root_style("ParagraphStyle", 7);
        let new = root_style("ParagraphStyle", 21);
        assert_eq!(old.attr("KeepFirstLines"), Some("2"));
        assert_eq!(old.attr("KeepAllLinesTogether"), Some("false"));
        assert!(old.attr("EmitCss").is_none());
        assert_eq!(new.attr("EmitCss"), Some("true"));
        let props = new.child("Properties").unwrap();
        assert!(props.child("RuleAboveType").is_some());
        assert!(props.child("ParagraphBorderType").is_some());
        let os = root_style("ObjectStyle", 21);
        assert!(
            os.child("TextFramePreference")
                .unwrap()
                .attr("TextColumnCount")
                .is_some()
        );
        assert!(
            os.child("TextFramePreference")
                .unwrap()
                .attr("AutoSizingType")
                .is_some()
        );
    }

    #[test]
    fn gates_preferences_by_version() {
        let old = preferences(7);
        let new = preferences(21);
        assert!(
            old.iter()
                .all(|n| n.tag != "EPubFixedLayoutExportPreference")
        );
        assert!(
            new.iter()
                .any(|n| n.tag == "EPubFixedLayoutExportPreference")
        );
        let text = new.iter().find(|n| n.tag == "TextDefault").unwrap();
        assert!(text.attr("PointSize").is_none());
        // Values the converter reads from the INDD are not in the file.
        let doc = new.iter().find(|n| n.tag == "DocumentPreference").unwrap();
        assert!(doc.attr("PageWidth").is_none());
    }
}
